apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{cronjobName}}
  namespace: {{namespace}}
spec:
  schedule: "{{schedule}}" # Example: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{cronjobName}}
              image: {{cronjobImage}}
              command: {{command}}
          restartPolicy: OnFailure
